# Generated by Django 5.1.5 on 2025-01-28 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cource_app', '0002_assignment_description_en_assignment_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': 'Teachers'},
        ),
    ]
