# Generated by Django 5.1.5 on 2025-01-28 06:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cource_app', '0003_alter_teacher_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='variants_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='variants_ru',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='experience',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(40)]),
        ),
    ]
