# Generated by Django 5.1.5 on 2025-02-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cource_app', '0004_option_variants_en_option_variants_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, null=True, upload_to='course_image'),
        ),
    ]
